"""Utility functions for TripMate AI."""

from src.utils.prompts import (
    INFO_COLLECTOR_SYSTEM_PROMPT,
    INFO_COLLECTOR_USER_PROMPT,
    ITINERARY_PLANNER_SYSTEM_PROMPT,
    ITINERARY_PLANNER_USER_PROMPT,
    RESPONSE_GENERATOR_SYSTEM_PROMPT,
    RESPONSE_GENERATOR_USER_PROMPT,
)

__all__ = [
    "INFO_COLLECTOR_SYSTEM_PROMPT",
    "INFO_COLLECTOR_USER_PROMPT",
    "ITINERARY_PLANNER_SYSTEM_PROMPT",
    "ITINERARY_PLANNER_USER_PROMPT",
    "RESPONSE_GENERATOR_SYSTEM_PROMPT",
    "RESPONSE_GENERATOR_USER_PROMPT",
]
